### ISSUE TITLE
The application is not adding the correct email, when the email column title is empty and there is another column called “column1”.

### ISSUE THREAD

**Issue by juacamar** [LorenzoRodriguezRivetlogic/csv-template-mailer#1]
Description:  When the email column title is empty the application replaces the rows that contains the emails for the values of the column named “column1”

-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1.Open the Liferay APP.
2.Create the next .csv file
https://www.screencast.com/t/6yx6FgpquNe

3. Load the file in the application
4. Select the column1 as the column that contains the email, select the first one.
5. Fill Out all the fills and click on the “show preview” button 
*Note in the preview that the fields on the column1 does not contain the emails.
6.Click on the send button.

CURRENT RESULT: 
==================== 
The application sends the emails to configured emails, but the information on the column1 contains the values of the other column named column1 instead the email.

EXPECTED RESULT: 
==================== 
The application sends the emails to configured emails, and the information on the column1 should contain the emails.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed in last commit
