### ISSUE TITLE
The application saves the template several times if the user clicks more than one time the save button.

### ISSUE THREAD

**Issue by juacamar** [LorenzoRodriguezRivetlogic/csv-template-mailer#2]
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 

Description:  The template is saved several times, when the user clicks one than 1 time the save button.

PRECONDITIONS: 
==================== 

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1.Open the Liferay APP.
2.Create the next .csv file
https://www.screencast.com/t/LlABgoUZGHt
3. Load the file in the application
4. Select the email as the column that contains the email.
5. In the name, fill with “Template”.
6.Click on the save button several times.
7.Review the templates drop list

CURRENT RESULT: 
==================== 
The application saves several times the template.

EXPECTED RESULT: 
==================== 
The application should only save the template 1 time.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed in last commit
