### ISSUE TITLE
An error is displayed when the "Use in HTML" checkboxes are disabled.

### ISSUE THREAD

**Issue by juacamar** [LorenzoRodriguezRivetlogic/csv-template-mailer#3]
Description:  The "Use in HTML" checkboxes can not be disabled.

-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1.Open the Liferay APP.
2.Create the next .csv file
https://www.screencast.com/t/LlABgoUZGHt
3. Load the file in the application
4. Select the email as the column that contains the email.
5. Unselect all the "Use in HTML" checkboxes”,except the email field.
6.Click on the “Continue Button”.

CURRENT RESULT: 
==================== 
The application returns to the main page and a “Portlet is temporarily unavailable.” error message is displayed.

EXPECTED RESULT: 
==================== 
The application should continue to the template page, and no errors should be displayed.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed in the last commit
